### ISSUE TITLE
Fails to build on OSX with catkin_make_isolated

### ISSUE THREAD

**Issue by kjeremy** [stonier/ecl_lite#7]
I'm trying to install the turtulebot_simulator on OSX and `ecl_time_lite` is failing to build.

==> Processing catkin package: 'ecl_time_lite'
==> Building with env: '/Users/aradroids/overlay_ws/devel_isolated/ecl_mpl/env.sh'
==> cmake /Users/aradroids/overlay_ws/src/ecl_lite/ecl_time_lite -DCATKIN_DEVEL_PREFIX=/Users/aradroids/overlay_ws/devel_isolated/ecl_time_lite -DCMAKE_INSTALL_PREFIX=/Users/aradroids/overlay_ws/install_isolated -G Unix Makefiles in '/Users/aradroids/overlay_ws/build_isolated/ecl_time_lite'
-- Using CATKIN_DEVEL_PREFIX: /Users/aradroids/overlay_ws/devel_isolated/ecl_time_lite
-- Using CMAKE_PREFIX_PATH: /Users/aradroids/overlay_ws/devel_isolated/ecl_mpl;/Users/aradroids/overlay_ws/devel_isolated/ecl_exceptions;/Users/aradroids/overlay_ws/devel_isolated/ecl_errors;/Users/aradroids/overlay_ws/devel_isolated/ecl_eigen;/Users/aradroids/overlay_ws/devel_isolated/ecl_config;/Users/aradroids/overlay_ws/devel_isolated/ecl_command_line;/Users/aradroids/overlay_ws/devel_isolated/ecl_build;/Users/aradroids/overlay_ws/devel_isolated/ecl_license;/Users/aradroids/overlay_ws/devel_isolated/depthimage_to_laserscan;/Users/aradroids/overlay_ws/devel_isolated/create_node;/Users/aradroids/overlay_ws/devel_isolated/create_driver;/Users/aradroids/overlay_ws/devel_isolated/create_description;/Users/aradroids/overlay_ws/devel_isolated/capabilities;/Users/aradroids/overlay_ws/devel_isolated/bfl;/opt/ros/indigo
-- This workspace overlays: /Users/aradroids/overlay_ws/devel_isolated/ecl_mpl;/Users/aradroids/overlay_ws/devel_isolated/ecl_exceptions;/Users/aradroids/overlay_ws/devel_isolated/ecl_errors;/Users/aradroids/overlay_ws/devel_isolated/ecl_eigen;/Users/aradroids/overlay_ws/devel_isolated/ecl_config;/Users/aradroids/overlay_ws/devel_isolated/ecl_command_line;/Users/aradroids/overlay_ws/devel_isolated/ecl_build;/Users/aradroids/overlay_ws/devel_isolated/ecl_license;/Users/aradroids/overlay_ws/devel_isolated/depthimage_to_laserscan;/Users/aradroids/overlay_ws/devel_isolated/create_node;/Users/aradroids/overlay_ws/devel_isolated/create_driver;/Users/aradroids/overlay_ws/devel_isolated/create_description;/Users/aradroids/overlay_ws/devel_isolated/capabilities;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/local/bin/python
-- Using default Python package layout
-- Using empy: /usr/local/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /Users/aradroids/overlay_ws/build_isolated/ecl_time_lite/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/local/bin/nosetests-2.7
-- catkin 0.6.14
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   ecl_time_lite

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/aradroids/overlay_ws/build_isolated/ecl_time_lite
==> make -j4 -l4 in '/Users/aradroids/overlay_ws/build_isolated/ecl_time_lite'
[ 85%] Built target ecl_time_lite
[100%] Building CXX object src/examples/CMakeFiles/demo_time_functions.dir/time_functions.cpp.o
/Users/aradroids/overlay_ws/src/ecl_lite/ecl_time_lite/src/examples/time_functions.cpp:99:42: error: 
      no member named 'get_date_string' in namespace 'ecl'
    std::cout << "Date String: " << ecl::get_date_string() << std::endl;
                                    ~~~~~^
1 error generated.
make[2]: **\* [src/examples/CMakeFiles/demo_time_functions.dir/time_functions.cpp.o] Error 1
make[1]: **\* [src/examples/CMakeFiles/demo_time_functions.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'ecl_time_lite': 
  Command '['/Users/aradroids/overlay_ws/devel_isolated/ecl_mpl/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /Users/aradroids/overlay_ws/build_isolated/ecl_time_lite && /Users/aradroids/overlay_ws/devel_isolated/ecl_mpl/env.sh make -j4 -l4

Command failed, exiting.

**Comment by stonier** [comment]
Does max osx have `strftime`?

**Comment by stonier** [comment]
Looks like it does...I pushed f4332b3b. That should make it available to macosx. Now building on the buildfarm version 0.61.1.

I haven't got a macosx for testing, so if that doesn't fix it, please reopen.
